{
    "1": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "2": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "3": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "4": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "5": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "6": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "7": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "8": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "9": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "03": "PUNJAB",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "10": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "34": "PUDUCHERRY",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "11": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    },
    "12": {
        "35": "ANDAMAN AND NICOBAR ISLANDS",
        "28": "ANDHRA PRADESH",
        "12": "ARUNACHAL PRADESH",
        "18": "ASSAM",
        "10": "BIHAR",
        "22": "CHHATTISGARH",
        "38": "DADAR & NAGAR HAVELI & DAMAN & DIU",
        "07": "DELHI",
        "30": "GOA",
        "24": "GUJARAT",
        "06": "HARYANA",
        "02": "HIMACHAL PRADESH",
        "01": "JAMMU AND KASHMIR",
        "20": "JHARKHAND",
        "29": "KARNATAKA",
        "32": "KERALA",
        "37": "LADAKH",
        "31": "LAKSHADWEEP",
        "23": "MADHYA PRADESH",
        "27": "MAHARASHTRA",
        "17": "MEGHALAYA",
        "15": "MIZORAM",
        "13": "NAGALAND",
        "21": "ODISHA",
        "03": "PUNJAB",
        "08": "RAJASTHAN",
        "11": "SIKKIM",
        "33": "TAMIL NADU",
        "36": "TELANGANA",
        "16": "TRIPURA",
        "09": "UTTAR PRADESH",
        "05": "UTTARAKHAND",
        "19": "WEST BENGAL"
    }
}